// Shared sector / industry options for client onboarding + edit forms.
// Curated to cover the breadth of clients TPS works with — including
// Sport, Solar and Renewable Energy. Alphabetised with "Other" pinned
// at the end so it always sorts last in the dropdown.
export const SECTORS: readonly string[] = [
  'Accounting & Tax',
  'Aerospace & Defence',
  'Agriculture & Farming',
  'Architecture',
  'Arts & Entertainment',
  'Automotive',
  'Aviation',
  'Banking',
  'Beauty & Cosmetics',
  'Biotech & Pharmaceuticals',
  'Charity & Non-Profit',
  'Chemicals',
  'Construction',
  'Consulting',
  'Consumer Goods (FMCG)',
  'Creative & Design',
  'Cybersecurity',
  'Data & Analytics',
  'E-commerce',
  'Education',
  'Energy (Oil & Gas)',
  'Engineering',
  'Environmental Services',
  'Events & Conferences',
  'Facilities Management',
  'Fashion & Apparel',
  'Finance & Investment',
  'Fitness & Wellness',
  'Food & Beverage',
  'Gaming',
  'Government & Public Sector',
  'Healthcare & Medical',
  'Hospitality & Tourism',
  'HR & Recruitment',
  'Insurance',
  'Legal Services',
  'Logistics & Supply Chain',
  'Manufacturing',
  'Marketing & Advertising',
  'Media & Publishing',
  'Mining',
  'Music',
  'Pet Care & Veterinary',
  'Print & Packaging',
  'Professional Services',
  'Property & Real Estate',
  'Renewable Energy',
  'Research & Development',
  'Retail',
  'Sales & Distribution',
  'Security',
  'Solar',
  'Sport',
  'Sports & Recreation',
  'Technology & SaaS',
  'Telecommunications',
  'Transportation',
  'Travel',
  'Utilities',
  'Waste Management',
  'Wholesale',
  'Other',
];
