import { NextRequest } from 'next/server';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { runCronJob } from '@/lib/automation/runs';
import { readAllPages } from '@/lib/supabase/paged';
import { computeValueReport } from '@/lib/valueReport/computeReport';
import { buildReportPdf } from '@/lib/valueReport/buildReportPdf';
import { sendKeyedEmail } from '@/lib/notify/keyedEmail';
import { valueReportEmail } from '@/lib/email';
import { portalUrl } from '@/lib/portalUrl';

// Monthly (08:00 UTC, 1st of the month): one Client Value Report PDF
// per active company for the month that just ended, stored in
// `reports` (the same table/row shape ReportUploadForm's manual path
// writes) and emailed. This is the same computeValueReport +
// buildReportPdf every staff download on /value-reports already uses
// — the cron generates what a person would have generated by hand,
// not a second version of the report.
//
// jsPDF + jspdf-autotable are imported normally here (Node runtime, no
// bundle-size concern) rather than the browser page's lazy `import()`
// — both are pure text/table renderers with no Canvas/DOM dependency,
// which is what makes them usable in a serverless Node function at all.

export const runtime = 'nodejs';
export const maxDuration = 60;
export const dynamic = 'force-dynamic';

function previousMonth(): { year: number; month: number; label: string } {
  const now = new Date();
  const d = new Date(now.getFullYear(), now.getMonth() - 1, 1);
  return { year: d.getFullYear(), month: d.getMonth(), label: d.toLocaleDateString('en-GB', { month: 'long', year: 'numeric' }) };
}

async function run(req: NextRequest) {
  return runCronJob(req, 'monthly-value-reports', async (sb) => {
    const { year, month, label: period } = previousMonth();

    const [
      companiesRes, reqsPage, candsPage, ticketsPage, docsPage, compliancePage,
      servReqsPage, actionsPage, profilesPage, servicesPage,
      trainingPage, reviewsPage, absencePage, onboardingPage,
    ] = await Promise.all([
      sb.from('companies').select('id, name, active, contact_email').eq('active', true).not('contact_email', 'is', null),
      readAllPages<any>((from, to) => sb.from('requisitions').select('id, company_id, title, stage, created_at, updated_at').order('id').range(from, to)),
      readAllPages<any>((from, to) => sb.from('candidates').select('id, company_id, full_name, client_status, created_at').order('id').range(from, to)),
      readAllPages<any>((from, to) => sb.from('tickets').select('id, company_id, subject, status, priority, created_at, resolved_at').order('id').range(from, to)),
      readAllPages<any>((from, to) => sb.from('documents').select('id, company_id, name, created_at').order('id').range(from, to)),
      readAllPages<any>((from, to) => sb.from('compliance_items').select('id, company_id, title, status, created_at').order('id').range(from, to)),
      readAllPages<any>((from, to) => sb.from('service_requests').select('id, company_id, subject, status, created_at, responded_at').order('id').range(from, to)),
      readAllPages<any>((from, to) => sb.from('actions').select('id, company_id, title, status, created_at, completed_at').order('id').range(from, to)),
      readAllPages<any>((from, to) => sb.from('profiles').select('id, company_id, role').neq('role', 'tps_admin').order('id').range(from, to)),
      readAllPages<any>((from, to) => sb.from('client_services').select('id, company_id, service_name, monthly_fee, status').eq('status', 'active').order('id').range(from, to)),
      readAllPages<any>((from, to) => sb.from('training_needs').select('id, company_id, status, created_at, updated_at').order('id').range(from, to)),
      readAllPages<any>((from, to) => sb.from('performance_reviews').select('id, company_id, status, due_date, completed_at, created_at').order('id').range(from, to)),
      readAllPages<any>((from, to) => sb.from('absence_records').select('id, company_id, status, start_date, days, created_at').eq('status', 'approved').order('id').range(from, to)),
      readAllPages<any>((from, to) => sb.from('onboarding_instances').select('id, company_id, status, started_at, completed_at').order('id').range(from, to)),
    ]);

    const companies = (companiesRes.data ?? []) as { id: string; name: string; contact_email: string }[];
    if (companiesRes.error) throw new Error(`companies: ${companiesRes.error.message}`);

    const inputs = {
      requisitions: reqsPage.rows, candidates: candsPage.rows, tickets: ticketsPage.rows, documents: docsPage.rows,
      complianceItems: compliancePage.rows, serviceRequests: servReqsPage.rows, actions: actionsPage.rows,
      profiles: profilesPage.rows, services: servicesPage.rows,
      trainingNeeds: trainingPage.rows, performanceReviews: reviewsPage.rows,
      absenceRecords: absencePage.rows, onboardingInstances: onboardingPage.rows,
    };

    let generated = 0, emailed = 0, alreadySent = 0;
    const failures: string[] = [];
    const reportsUrl = `${portalUrl()}/protect/reports`;

    for (const company of companies) {
      try {
        const data = computeValueReport(company.id, year, month, inputs);
        const doc = buildReportPdf(jsPDF as any, autoTable as any, {
          companyName: company.name, month: period, generatedAt: new Date(), data,
        });
        const bytes = (doc as any).output('arraybuffer') as ArrayBuffer;

        const safeName = company.name.replace(/\s+/g, '-').replace(/[^a-zA-Z0-9._-]/g, '');
        const path = `reports/${company.id}/${Date.now()}_value-report-${year}-${String(month + 1).padStart(2, '0')}-${safeName}.pdf`;

        const { error: uploadErr } = await sb.storage.from('documents')
          .upload(path, Buffer.from(bytes), { contentType: 'application/pdf', upsert: false });
        if (uploadErr) { failures.push(`${company.name}: upload failed (${uploadErr.message})`); continue; }

        const { error: insertErr } = await sb.from('reports').insert({
          company_id: company.id,
          title: `${period} Value Report`,
          period,
          storage_path: path,
          file_url: null,
          generated_by: null, // system-generated: no human in the loop (108)
        });
        if (insertErr) { failures.push(`${company.name}: reports insert failed (${insertErr.message})`); continue; }
        generated++;

        const message = valueReportEmail({ to: company.contact_email, companyName: company.name, period, reportsUrl });
        const result = await sendKeyedEmail(sb, {
          dedupeKey: `value-report:${company.id}:${year}-${month}`,
          to: message.to, subject: message.subject, html: message.html, tag: message.tag,
          target: { type: 'company', id: company.id }, companyId: company.id,
        });
        if (result.outcome === 'sent') emailed++;
        else if (result.outcome === 'already') alreadySent++;
        else failures.push(`${company.name}: email failed (${result.error})`);
      } catch (err) {
        failures.push(`${company.name}: ${(err as Error).message}`);
      }
    }

    const tally = { period, companies: companies.length, generated, emailed, alreadySent, failures };
    return { tally, degraded: failures.length > 0 };
  });
}

export async function GET(req: NextRequest)  { return run(req); }
export async function POST(req: NextRequest) { return run(req); }
