// Core-OS 360 Phase 12, Group 1: Compliance Digital Twin.
//
// A "digital twin" here means exactly one thing: a single, read-time,
// deterministic model of a client's ENTIRE compliance state, assembled
// from five modules this codebase already has — never a new raw fact.
// This file adds no new data computation of its own. Its only new logic
// is (a) a per-area RAG (red/amber/green) band, derived by fixed,
// documented numeric thresholds — the same `if`-chain-over-named-
// thresholds shape lib/health/scoring.ts's own computeBand() already
// uses, never a formula or a score — and (b) combining the five areas
// into one snapshot with an overall band (the worst of the five).
//
// Every "reason" attached to a band is a plain sentence built directly
// from a number one of the five source modules already computed — never
// an AI narrative, never a summary generated by a model. This is the
// same absolute rule Phase 10's own header comment states: report what
// has ALREADY happened, in the past tense, with a real inspectable count
// behind it, never a probability or a "likely to recur" framing.
//
// Source modules (each already reads its own rows and computes its own
// facts; this file only combines their OUTPUTS):
//   - lib/hs/kpis.ts               (computeHsKpis, Phase 4)
//   - lib/governance/kpis.ts       (computeGovernanceKpis, Phase 5 Gp 8)
//   - lib/riskGraph/intelligence.ts (computeRiskGraphIntelligence, Phase 8)
//   - lib/incidentPatterns/analyze.ts (analyzeIncidentPatterns, Phase 10)
//   - lib/evidenceEngine/analyze.ts   (analyzeEvidenceCoverage, Phase 11)

import type { RiskGraphIntelligence } from '@/lib/riskGraph/intelligence';
import type { IncidentPatternSummary } from '@/lib/incidentPatterns/analyze';
import type { EvidenceCoverageSummary } from '@/lib/evidenceEngine/analyze';

// lib/hs/kpis.ts and lib/governance/kpis.ts are admin-only (there is no
// portal copy of either, checked before writing this file) — this
// shared-dupe pair cannot import their types the way it imports the
// three genuinely-shared modules below. These two interfaces name only
// the fields this file actually reads, structurally compatible with
// admin's own HsKpis/GovernanceKpis so the admin page can pass either
// straight through with no mapping step.
export interface ComplianceTwinHsKpisInput {
  equipmentOverdueCount: number;
  equipmentDueSoonCount: number;
  riddorLast12Months: number;
  lastAuditScore: number | null;
}

export interface ComplianceTwinGovernanceKpisInput {
  overdueLegalEvaluationsCount: number;
  objectivesOnTrackPercent: number | null;
  wasteNonConformancePercent: number | null;
}

export type ComplianceTwinBand = 'red' | 'amber' | 'green';

export type ComplianceTwinAreaKey = 'safety' | 'governance' | 'risk_graph' | 'incident_patterns' | 'evidence';

export interface ComplianceTwinArea {
  area: ComplianceTwinAreaKey;
  label: string;
  band: ComplianceTwinBand;
  /** Plain sentences built from the underlying numbers — never AI-generated. */
  reasons: string[];
}

export interface ComplianceTwinSnapshot {
  overallBand: ComplianceTwinBand;
  areas: ComplianceTwinArea[];
}

export interface ComplianceTwinInput {
  hsKpis: ComplianceTwinHsKpisInput;
  governanceKpis: ComplianceTwinGovernanceKpisInput;
  riskGraph: RiskGraphIntelligence;
  incidentPatterns: IncidentPatternSummary;
  evidence: EvidenceCoverageSummary;
}

// Thresholds. Named and documented rather than inlined, and reused from
// an existing precedent where one already exists in this codebase.
const AUDIT_SCORE_LOW_THRESHOLD = 70; // Phase 5 Group 6's management-review data pack already uses "audits scoring below 70%"
const EVIDENCE_RED_THRESHOLD = 50;
const EVIDENCE_AMBER_THRESHOLD = 90;
const OBJECTIVES_ON_TRACK_AMBER_THRESHOLD = 50;
const WASTE_NON_CONFORMANCE_AMBER_THRESHOLD = 10; // percent

const BAND_SEVERITY: Record<ComplianceTwinBand, number> = { green: 0, amber: 1, red: 2 };

function worstBand(bands: ComplianceTwinBand[]): ComplianceTwinBand {
  let worst: ComplianceTwinBand = 'green';
  for (const b of bands) if (BAND_SEVERITY[b] > BAND_SEVERITY[worst]) worst = b;
  return worst;
}

/**
 * Combines a red-reasons list and an amber-reasons list into one area
 * entry. Both lists are built unconditionally from their own
 * independent checks — never short-circuited by an earlier check
 * already having tripped the band to red — so an area that is red for
 * one reason still reports every amber-level fact that is ALSO true,
 * rather than hiding it behind the worse finding.
 */
function buildArea(
  area: ComplianceTwinAreaKey,
  label: string,
  redReasons: string[],
  amberReasons: string[],
  cleanReason: string,
): ComplianceTwinArea {
  const band = worstBand([
    ...redReasons.map(() => 'red' as const),
    ...amberReasons.map(() => 'amber' as const),
  ]);
  const reasons =
    band === 'red' ? [...redReasons, ...amberReasons] : band === 'amber' ? amberReasons : [cleanReason];
  return { area, label, band, reasons };
}

function safetyArea(k: ComplianceTwinHsKpisInput): ComplianceTwinArea {
  const red: string[] = [];
  const amber: string[] = [];

  if (k.riddorLast12Months > 0) {
    red.push(`${k.riddorLast12Months} RIDDOR-reportable incident(s) recorded in the last 12 months`);
  }
  if (k.equipmentOverdueCount > 0) {
    red.push(`${k.equipmentOverdueCount} equipment item(s) overdue for inspection`);
  }
  if (k.equipmentDueSoonCount > 0) {
    amber.push(`${k.equipmentDueSoonCount} equipment item(s) due for inspection within 30 days`);
  }
  if (k.lastAuditScore != null && k.lastAuditScore < AUDIT_SCORE_LOW_THRESHOLD) {
    amber.push(`Last audit scored ${k.lastAuditScore}%, below the ${AUDIT_SCORE_LOW_THRESHOLD}% threshold`);
  }

  return buildArea(
    'safety',
    'Safety (H&S)',
    red,
    amber,
    'No RIDDOR incidents, no overdue or soon-due equipment inspections, and the last audit score (if any) is at or above threshold',
  );
}

function governanceArea(k: ComplianceTwinGovernanceKpisInput): ComplianceTwinArea {
  const red: string[] = [];
  const amber: string[] = [];

  if (k.overdueLegalEvaluationsCount > 0) {
    red.push(`${k.overdueLegalEvaluationsCount} applicable legal obligation(s) with an overdue review`);
  }
  if (k.objectivesOnTrackPercent != null && k.objectivesOnTrackPercent < OBJECTIVES_ON_TRACK_AMBER_THRESHOLD) {
    amber.push(`Only ${Math.round(k.objectivesOnTrackPercent)}% of active objectives are on track or achieved`);
  }
  if (
    k.wasteNonConformancePercent != null &&
    k.wasteNonConformancePercent > WASTE_NON_CONFORMANCE_AMBER_THRESHOLD
  ) {
    amber.push(`${Math.round(k.wasteNonConformancePercent)}% of recorded waste movements were flagged non-conformant`);
  }

  return buildArea(
    'governance',
    'Governance & Environmental',
    red,
    amber,
    'No overdue legal obligation reviews, objectives are on track, and recorded waste non-conformance is within range',
  );
}

function riskGraphArea(g: RiskGraphIntelligence): ComplianceTwinArea {
  const red: string[] = [];
  const amber: string[] = [];

  if (g.assessmentsWithIneffectiveControls.length > 0) {
    red.push(
      `${g.assessmentsWithIneffectiveControls.length} currently-relied-on risk assessment(s) carry a control recorded as ineffective`,
    );
  }
  if (g.uncoveredHazards.length > 0) {
    amber.push(`${g.uncoveredHazards.length} hazard(s) have no risk assessment coverage`);
  }
  if (g.ineffectiveSharedControls.length > 0) {
    amber.push(
      `${g.ineffectiveSharedControls.length} control(s) shared across multiple risk assessments are recorded as ineffective`,
    );
  }
  if (g.unlinkedApplicableObligations.length > 0) {
    amber.push(
      `${g.unlinkedApplicableObligations.length} applicable legal obligation(s) have no linked risk assessment or hazard`,
    );
  }

  return buildArea(
    'risk_graph',
    'Risk Graph',
    red,
    amber,
    'Every hazard is covered, no ineffective controls, and every applicable legal obligation is linked',
  );
}

function incidentPatternsArea(p: IncidentPatternSummary): ComplianceTwinArea {
  const red: string[] = [];
  const amber: string[] = [];

  if (p.severityComparison.currentWindow.fatal > 0) {
    red.push(`${p.severityComparison.currentWindow.fatal} fatal incident(s) recorded in the current window`);
  }
  if (p.severityComparison.currentWindow.critical > 0) {
    red.push(`${p.severityComparison.currentWindow.critical} critical incident(s) recorded in the current window`);
  }
  if (p.recurringRootCauses.length > 0) {
    amber.push(`${p.recurringRootCauses.length} recurring confirmed root cause category(ies) across 2+ incidents`);
  }
  if (p.siteClusters.length > 0) {
    amber.push(`${p.siteClusters.length} site(s) with 2+ incidents in the current window`);
  }
  if (p.departmentClusters.length > 0) {
    amber.push(`${p.departmentClusters.length} department(s) with 2+ incidents in the current window`);
  }
  if (p.severityComparison.currentWindow.major > p.severityComparison.priorWindow.major) {
    amber.push(
      `Major-severity incidents increased from ${p.severityComparison.priorWindow.major} to ${p.severityComparison.currentWindow.major} versus the prior window`,
    );
  }

  return buildArea(
    'incident_patterns',
    'Incident Patterns',
    red,
    amber,
    'No fatal or critical incidents, no recurring root causes or location clusters, and major-severity incidents are not worsening',
  );
}

function evidenceArea(e: EvidenceCoverageSummary): ComplianceTwinArea {
  const red: string[] = [];
  const amber: string[] = [];

  if (e.coveragePercent != null && e.coveragePercent < EVIDENCE_RED_THRESHOLD) {
    red.push(`Evidence coverage is ${Math.round(e.coveragePercent)}%, below the ${EVIDENCE_RED_THRESHOLD}% threshold`);
  }
  if (e.coveragePercent != null && e.coveragePercent < EVIDENCE_AMBER_THRESHOLD) {
    amber.push(
      `Evidence coverage is ${Math.round(e.coveragePercent)}%, below the ${EVIDENCE_AMBER_THRESHOLD}% threshold`,
    );
  }

  return buildArea(
    'evidence',
    'Evidence Coverage',
    red,
    amber,
    'Evidence coverage is at or above the 90% threshold (or no register completions have been recorded yet)',
  );
}

export function assembleComplianceTwin(input: ComplianceTwinInput): ComplianceTwinSnapshot {
  const areas: ComplianceTwinArea[] = [
    safetyArea(input.hsKpis),
    governanceArea(input.governanceKpis),
    riskGraphArea(input.riskGraph),
    incidentPatternsArea(input.incidentPatterns),
    evidenceArea(input.evidence),
  ];

  return { overallBand: worstBand(areas.map(a => a.band)), areas };
}
