import type { Metadata } from 'next';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import Topbar from '@/components/layout/Topbar';
import { BarChart3, Download } from 'lucide-react';

export const metadata: Metadata = { title: 'Reports' };

export default async function ReportsPage() {
  const supabase = createServerSupabaseClient();
  const { data: { user } } = await supabase.auth.getUser();
  const { data: profile }  = await supabase.from('profiles').select('company_id').eq('id', user?.id ?? '').single();
  const companyId: string  = (profile as any)?.company_id ?? '';

  const { data: reports } = await supabase
    .from('reports')
    .select('*')
    .eq('company_id', companyId)
    .order('created_at', { ascending: false });

  const all = reports ?? [];

  return (
    <>
      <Topbar title="Reports" subtitle={`${all.length} report${all.length !== 1 ? 's' : ''} available`} />
      <main className="portal-page flex-1">
        {all.length === 0 ? (
          <div className="card p-12">
            <div className="empty-state">
              <BarChart3 size={28} />
              <p className="text-base font-medium" style={{ color: 'var(--ink-soft)' }}>No reports yet</p>
              <p className="text-sm max-w-[320px]" style={{ color: 'var(--ink-faint)' }}>
                Reports generated by Ravello will appear here. They can be downloaded as PDFs.
              </p>
            </div>
          </div>
        ) : (
          <div className="table-wrapper">
            <table className="table">
              <thead>
                <tr>
                  <th>Report</th>
                  <th>Period</th>
                  <th>Generated</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                {all.map((r: any) => (
                  <tr key={r.id}>
                    <td>
                      <p className="font-medium text-sm" style={{ color: 'var(--ink)' }}>{r.title}</p>
                    </td>
                    <td style={{ color: 'var(--ink-soft)' }}>{r.period ?? '—'}</td>
                    <td style={{ color: 'var(--ink-faint)' }}>{new Date(r.created_at).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}</td>
                    <td>
                      <a
                        href={r.file_url}
                        download
                        target="_blank"
                        rel="noopener noreferrer"
                        className="btn-secondary btn-sm flex items-center gap-1.5"
                      >
                        <Download size={13} /> Download
                      </a>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </main>
    </>
  );
}
