import Link from 'next/link';
import { ArrowRight, FolderOpen, BarChart3, LifeBuoy, Briefcase } from 'lucide-react';

const modules = [
  {
    icon: Briefcase,
    label: 'Hiring Tracking',
    desc: 'Live pipeline view. See every role, every candidate, every status — updated in real time.',
    accent: 'var(--brand-purple)',
  },
  {
    icon: FolderOpen,
    label: 'Document Management',
    desc: 'Store, categorise, and version-control HR documents. Contracts, policies, letters — in one place.',
    accent: 'var(--brand-blue)',
  },
  {
    icon: BarChart3,
    label: 'Reports',
    desc: 'Access HR and hiring reports generated by Ravello. Download, share, or review in-portal.',
    accent: 'var(--brand-teal)',
  },
  {
    icon: LifeBuoy,
    label: 'Support Requests',
    desc: 'Submit HR queries and track them through to resolution. No lost emails, no chasing.',
    accent: 'var(--brand-pink)',
  },
];

export default function PortalTeaser() {
  return (
    <section className="section-padding section-light">
      <div className="container-wide">

        <div className="grid lg:grid-cols-2 gap-16 items-center">

          {/* Left — mock portal UI */}
          <div className="relative">
            <div
              className="rounded-[24px] overflow-hidden"
              style={{
                background: 'var(--brand-navy)',
                boxShadow: '0 8px 60px rgba(14,22,51,0.25)',
              }}
            >
              {/* Portal header bar */}
              <div
                className="flex items-center justify-between px-6 py-4"
                style={{ borderBottom: '1px solid rgba(255,255,255,0.07)' }}
              >
                <div className="flex items-center gap-2">
                  <span className="text-sm font-semibold text-white">Ravello Portal</span>
                  <span className="pill-purple text-[10px] ml-1">Client</span>
                </div>
                <div className="flex items-center gap-1.5">
                  <div className="w-2 h-2 rounded-full bg-emerald-400" />
                  <span className="text-[11px]" style={{ color: 'rgba(255,255,255,0.4)' }}>Live</span>
                </div>
              </div>

              {/* Dashboard content */}
              <div className="p-6 space-y-3">
                {/* Summary row */}
                <div className="grid grid-cols-3 gap-3">
                  {[
                    { label: 'Active Roles', val: '3' },
                    { label: 'Open Docs',    val: '12' },
                    { label: 'HR Items',     val: '2' },
                  ].map((stat) => (
                    <div
                      key={stat.label}
                      className="rounded-[12px] p-3 text-center"
                      style={{ background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.07)' }}
                    >
                      <p className="font-display font-bold text-xl text-white">{stat.val}</p>
                      <p className="text-[10px] mt-0.5" style={{ color: 'rgba(255,255,255,0.35)' }}>{stat.label}</p>
                    </div>
                  ))}
                </div>

                {/* Pipeline preview */}
                <div
                  className="rounded-[14px] p-4"
                  style={{ background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.07)' }}
                >
                  <p className="text-[10px] font-semibold uppercase tracking-[0.14em] mb-3" style={{ color: 'rgba(255,255,255,0.3)' }}>
                    Hiring Pipeline
                  </p>
                  {[
                    { role: 'Finance Manager',    stage: 'Shortlist Ready', badge: 'status-shortlist' },
                    { role: 'Head of Operations', stage: 'In Progress',     badge: 'status-inprogress' },
                    { role: 'Account Executive',  stage: 'Interview',       badge: 'status-interview' },
                  ].map((r) => (
                    <div key={r.role} className="flex items-center justify-between py-2">
                      <span className="text-xs text-white">{r.role}</span>
                      <span className={`status-badge ${r.badge}`}>{r.stage}</span>
                    </div>
                  ))}
                </div>

                {/* Notification */}
                <div
                  className="rounded-[12px] px-4 py-3 flex items-center gap-3"
                  style={{
                    background: 'rgba(143,114,246,0.12)',
                    border: '1px solid rgba(143,114,246,0.2)',
                  }}
                >
                  <div className="w-1.5 h-1.5 rounded-full flex-shrink-0 bg-purple-400" />
                  <p className="text-xs" style={{ color: 'rgba(255,255,255,0.7)' }}>
                    Employee handbook — review due in 7 days
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Right — copy */}
          <div>
            <p className="eyebrow mb-4">The client portal</p>
            <h2 className="display-lg mb-6" style={{ color: 'var(--ink)' }}>
              Your HR and hiring activity — in one place.
            </h2>
            <p className="text-base leading-relaxed mb-8" style={{ color: 'var(--ink-soft)' }}>
              Every Ravello client gets access to a private portal. It replaces the inbox threads, shared
              drives, and spreadsheets that most businesses run HR on. One login. Everything visible.
            </p>

            <div className="grid sm:grid-cols-2 gap-4 mb-8">
              {modules.map((m) => (
                <div
                  key={m.label}
                  className="flex gap-3 rounded-[14px] p-4"
                  style={{ background: 'var(--surface-alt)', border: '1px solid var(--brand-line)' }}
                >
                  <div
                    className="w-8 h-8 rounded-[8px] flex items-center justify-center flex-shrink-0"
                    style={{
                      background: `color-mix(in srgb, ${m.accent} 12%, transparent)`,
                    }}
                  >
                    <m.icon size={15} style={{ color: m.accent }} />
                  </div>
                  <div>
                    <p className="text-xs font-semibold mb-1" style={{ color: 'var(--ink)' }}>{m.label}</p>
                    <p className="text-[11px] leading-relaxed" style={{ color: 'var(--ink-faint)' }}>{m.desc}</p>
                  </div>
                </div>
              ))}
            </div>

            <Link href="/contact" className="btn-primary">
              Request portal access <ArrowRight size={15} />
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
}
