-- Core-OS 360 Phase 6, Group 6 (section 10: Value Report).
--
-- A consultant reviewing a client's quarter needs to say something
-- in their own words alongside the numbers -- "we focused on X this
-- quarter, Y is now on track, watch Z next quarter" -- not just the
-- computed metric grid computeValueReport()/computeQuarterlyValueReport()
-- already produce. This adds exactly one nullable column to carry
-- that free text; it is never read by any computation, never fed to
-- Jev, and never asserted as a fact -- it is the human commentary
-- alongside the deterministic numbers, the same "AI/database computes
-- the facts, a person writes the narrative" split this codebase
-- already draws throughout Phase 5's governance tables.
--
-- reports.narrative is nullable and additive: every existing row
-- (uploaded via ReportUploadForm.tsx, or generated by the monthly
-- cron before this migration) simply has narrative = NULL, and every
-- existing reader of `reports` (the portal's /protect/reports page,
-- ClientDetailTabs, the monthly-value-reports cron route) is
-- unaffected -- none of them selected '*' blindly; each names its own
-- columns, so this column appears nowhere until a caller asks for it.

ALTER TABLE public.reports ADD COLUMN IF NOT EXISTS narrative TEXT;

COMMENT ON COLUMN public.reports.narrative IS
  'Optional consultant-written commentary alongside the report''s own computed metrics. Never computed, never read by any rule or automation -- human text only.';
