// Core-OS 360 Phase 12, Group 1: Compliance Digital Twin.
//
// A "digital twin" here means exactly one thing: a single, read-time,
// deterministic model of a client's ENTIRE compliance state, assembled
// from five modules this codebase already has — never a new raw fact.
// This file adds no new data computation of its own. Its only new logic
// is (a) a per-area RAG (red/amber/green) band, derived by fixed,
// documented numeric thresholds — the same `if`-chain-over-named-
// thresholds shape lib/health/scoring.ts's own computeBand() already
// uses, never a formula or a score — and (b) combining the five areas
// into one snapshot with an overall band (the worst of the five).
//
// Every "reason" attached to a band is a plain sentence built directly
// from a number one of the five source modules already computed — never
// an AI narrative, never a summary generated by a model. This is the
// same absolute rule Phase 10's own header comment states: report what
// has ALREADY happened, in the past tense, with a real inspectable count
// behind it, never a probability or a "likely to recur" framing.
//
// Source modules (each already reads its own rows and computes its own
// facts; this file only combines their OUTPUTS):
//   - lib/hs/kpis.ts               (computeHsKpis, Phase 4)
//   - lib/governance/kpis.ts       (computeGovernanceKpis, Phase 5 Gp 8)
//   - lib/riskGraph/intelligence.ts (computeRiskGraphIntelligence, Phase 8)
//   - lib/incidentPatterns/analyze.ts (analyzeIncidentPatterns, Phase 10)
//   - lib/evidenceEngine/analyze.ts   (analyzeEvidenceCoverage, Phase 11)

import type { HsKpis } from '@/lib/hs/kpis';
import type { GovernanceKpis } from '@/lib/governance/kpis';
import type { RiskGraphIntelligence } from '@/lib/riskGraph/intelligence';
import type { IncidentPatternSummary } from '@/lib/incidentPatterns/analyze';
import type { EvidenceCoverageSummary } from '@/lib/evidenceEngine/analyze';

// lib/hs/kpis.ts and lib/governance/kpis.ts were admin-only until this
// group needed both in portal too, for exactly this page — both are now
// shared-dupe pairs (checked: neither has any admin-specific dependency,
// governance/kpis.ts has no imports at all and hs/kpis.ts only imports
// the already-shared recurrence.ts), so this file imports their real
// types directly rather than declaring a duplicate narrower interface.

export type ComplianceTwinBand = 'red' | 'amber' | 'green';

export type ComplianceTwinAreaKey = 'safety' | 'governance' | 'risk_graph' | 'incident_patterns' | 'evidence';

export interface ComplianceTwinArea {
  area: ComplianceTwinAreaKey;
  label: string;
  band: ComplianceTwinBand;
  /** Plain sentences built from the underlying numbers — never AI-generated. */
  reasons: string[];
  /**
   * Core-OS 360 Completion Programme, Phase 23, Group 6 (closes
   * gap-ledger row C12.6): the exact raw values this area's own
   * red/amber checks read — never a re-derivation, the same numbers
   * already driving `reasons`, just also exposed structurally. Any
   * threshold actually used (post-override, Group 5) is included
   * alongside the value it was compared against.
   */
  inputs: Record<string, number | string | null>;
}

export interface ComplianceTwinSnapshot {
  overallBand: ComplianceTwinBand;
  areas: ComplianceTwinArea[];
}

export interface ComplianceTwinInput {
  hsKpis: HsKpis;
  governanceKpis: GovernanceKpis;
  riskGraph: RiskGraphIntelligence;
  incidentPatterns: IncidentPatternSummary;
  evidence: EvidenceCoverageSummary;
}

/**
 * Core-OS 360 Completion Programme, Phase 23, Group 5 (closes
 * gap-ledger row C12.5): a nullable per-company override for each
 * named threshold below. `null`/`undefined` always falls back to the
 * documented default, never silently guessed — deciding these
 * thresholds decides what a CLIENT sees as red/amber/green on their
 * own posture, so an override is only ever staff-set
 * (compliance_twin_thresholds, migration 189, staff-only RLS), never
 * client-writable.
 */
export interface ComplianceTwinThresholds {
  auditScoreLowThreshold?: number | null;
  evidenceRedThreshold?: number | null;
  evidenceAmberThreshold?: number | null;
  objectivesOnTrackAmberThreshold?: number | null;
  wasteNonConformanceAmberThreshold?: number | null;
}

// Default thresholds. Named and documented rather than inlined, and
// reused from an existing precedent where one already exists in this
// codebase. Each may be overridden per company via ComplianceTwinThresholds.
const DEFAULT_AUDIT_SCORE_LOW_THRESHOLD = 70; // Phase 5 Group 6's management-review data pack already uses "audits scoring below 70%"
const DEFAULT_EVIDENCE_RED_THRESHOLD = 50;
const DEFAULT_EVIDENCE_AMBER_THRESHOLD = 90;
const DEFAULT_OBJECTIVES_ON_TRACK_AMBER_THRESHOLD = 50;
const DEFAULT_WASTE_NON_CONFORMANCE_AMBER_THRESHOLD = 10; // percent

const BAND_SEVERITY: Record<ComplianceTwinBand, number> = { green: 0, amber: 1, red: 2 };

function worstBand(bands: ComplianceTwinBand[]): ComplianceTwinBand {
  let worst: ComplianceTwinBand = 'green';
  for (const b of bands) if (BAND_SEVERITY[b] > BAND_SEVERITY[worst]) worst = b;
  return worst;
}

/**
 * Combines a red-reasons list and an amber-reasons list into one area
 * entry. Both lists are built unconditionally from their own
 * independent checks — never short-circuited by an earlier check
 * already having tripped the band to red — so an area that is red for
 * one reason still reports every amber-level fact that is ALSO true,
 * rather than hiding it behind the worse finding.
 */
function buildArea(
  area: ComplianceTwinAreaKey,
  label: string,
  redReasons: string[],
  amberReasons: string[],
  cleanReason: string,
  inputs: Record<string, number | string | null>,
): ComplianceTwinArea {
  const band = worstBand([
    ...redReasons.map(() => 'red' as const),
    ...amberReasons.map(() => 'amber' as const),
  ]);
  const reasons =
    band === 'red' ? [...redReasons, ...amberReasons] : band === 'amber' ? amberReasons : [cleanReason];
  return { area, label, band, reasons, inputs };
}

function safetyArea(k: HsKpis, thresholds?: ComplianceTwinThresholds): ComplianceTwinArea {
  const auditScoreLowThreshold = thresholds?.auditScoreLowThreshold ?? DEFAULT_AUDIT_SCORE_LOW_THRESHOLD;
  const red: string[] = [];
  const amber: string[] = [];

  if (k.riddorLast12Months > 0) {
    red.push(`${k.riddorLast12Months} RIDDOR-reportable incident(s) recorded in the last 12 months`);
  }
  if (k.equipmentOverdueCount > 0) {
    red.push(`${k.equipmentOverdueCount} equipment item(s) overdue for inspection`);
  }
  if (k.equipmentDueSoonCount > 0) {
    amber.push(`${k.equipmentDueSoonCount} equipment item(s) due for inspection within 30 days`);
  }
  if (k.lastAuditScore != null && k.lastAuditScore < auditScoreLowThreshold) {
    // hs_audits.score is always an integer today (hs_submit_audit()
    // rounds it, and that RPC is the table's only writer — checked
    // before deciding this needed no Math.round of its own). Rounded
    // here anyway for the same defensive consistency every other
    // percentage in this file already has, in case a future writer
    // ever stores a fractional score.
    amber.push(`Last audit scored ${Math.round(k.lastAuditScore)}%, below the ${auditScoreLowThreshold}% threshold`);
  }

  return buildArea(
    'safety',
    'Safety (H&S)',
    red,
    amber,
    'No RIDDOR incidents, no overdue or soon-due equipment inspections, and the last audit score (if any) is at or above threshold',
    {
      riddorLast12Months: k.riddorLast12Months,
      equipmentOverdueCount: k.equipmentOverdueCount,
      equipmentDueSoonCount: k.equipmentDueSoonCount,
      lastAuditScore: k.lastAuditScore,
      auditScoreLowThreshold,
    },
  );
}

function governanceArea(k: GovernanceKpis, thresholds?: ComplianceTwinThresholds): ComplianceTwinArea {
  const objectivesOnTrackAmberThreshold = thresholds?.objectivesOnTrackAmberThreshold ?? DEFAULT_OBJECTIVES_ON_TRACK_AMBER_THRESHOLD;
  const wasteNonConformanceAmberThreshold = thresholds?.wasteNonConformanceAmberThreshold ?? DEFAULT_WASTE_NON_CONFORMANCE_AMBER_THRESHOLD;
  const red: string[] = [];
  const amber: string[] = [];

  if (k.overdueLegalEvaluationsCount > 0) {
    red.push(`${k.overdueLegalEvaluationsCount} applicable legal obligation(s) with an overdue review`);
  }
  if (k.objectivesOnTrackPercent != null && k.objectivesOnTrackPercent < objectivesOnTrackAmberThreshold) {
    amber.push(`Only ${Math.round(k.objectivesOnTrackPercent)}% of active objectives are on track or achieved`);
  }
  if (
    k.wasteNonConformancePercent != null &&
    k.wasteNonConformancePercent > wasteNonConformanceAmberThreshold
  ) {
    amber.push(`${Math.round(k.wasteNonConformancePercent)}% of recorded waste movements were flagged non-conformant`);
  }

  return buildArea(
    'governance',
    'Governance & Environmental',
    red,
    amber,
    // Found in Group 3's own adversarial review: unlike the other four
    // areas' clean reasons, which are all built from plain COUNTS (a
    // count of zero is unambiguous whether or not anything was ever
    // recorded), this area's two amber checks are PERCENTAGES that are
    // null with no data at all — the same shape lib/hs/kpis.ts's own
    // audit score and lib/evidenceEngine/analyze.ts's own coverage
    // percent already carry an explicit "(if any)"/"(or none recorded)"
    // caveat for. The original wording here ("objectives are on track")
    // read as a verified positive claim even for a client with zero
    // objectives and zero waste movements ever recorded — indistinguishable
    // from a client whose objectives were genuinely checked and found on
    // track. Reworded so a lack of data is never presented as a
    // confirmed good state, matching this codebase's standing rule that
    // absence of evidence is not evidence of a positive finding.
    'No overdue legal obligation reviews on record, and no evidence of objectives falling behind or elevated waste non-conformance',
    {
      overdueLegalEvaluationsCount: k.overdueLegalEvaluationsCount,
      objectivesOnTrackPercent: k.objectivesOnTrackPercent,
      objectivesOnTrackAmberThreshold,
      wasteNonConformancePercent: k.wasteNonConformancePercent,
      wasteNonConformanceAmberThreshold,
    },
  );
}

function riskGraphArea(g: RiskGraphIntelligence): ComplianceTwinArea {
  const red: string[] = [];
  const amber: string[] = [];

  if (g.assessmentsWithIneffectiveControls.length > 0) {
    red.push(
      `${g.assessmentsWithIneffectiveControls.length} currently-relied-on risk assessment(s) carry a control recorded as ineffective`,
    );
  }
  if (g.uncoveredHazards.length > 0) {
    amber.push(`${g.uncoveredHazards.length} hazard(s) have no risk assessment coverage`);
  }
  if (g.ineffectiveSharedControls.length > 0) {
    amber.push(
      `${g.ineffectiveSharedControls.length} control(s) shared across multiple risk assessments are recorded as ineffective`,
    );
  }
  if (g.unlinkedApplicableObligations.length > 0) {
    amber.push(
      `${g.unlinkedApplicableObligations.length} applicable legal obligation(s) have no linked risk assessment or hazard`,
    );
  }

  return buildArea(
    'risk_graph',
    'Risk Graph',
    red,
    amber,
    'Every hazard is covered, no ineffective controls, and every applicable legal obligation is linked',
    {
      assessmentsWithIneffectiveControlsCount: g.assessmentsWithIneffectiveControls.length,
      uncoveredHazardsCount: g.uncoveredHazards.length,
      ineffectiveSharedControlsCount: g.ineffectiveSharedControls.length,
      unlinkedApplicableObligationsCount: g.unlinkedApplicableObligations.length,
    },
  );
}

function incidentPatternsArea(p: IncidentPatternSummary): ComplianceTwinArea {
  const red: string[] = [];
  const amber: string[] = [];

  if (p.severityComparison.currentWindow.fatal > 0) {
    red.push(`${p.severityComparison.currentWindow.fatal} fatal incident(s) recorded in the current window`);
  }
  if (p.severityComparison.currentWindow.critical > 0) {
    red.push(`${p.severityComparison.currentWindow.critical} critical incident(s) recorded in the current window`);
  }
  if (p.recurringRootCauses.length > 0) {
    amber.push(`${p.recurringRootCauses.length} recurring confirmed root cause category(ies) across 2+ incidents`);
  }
  if (p.siteClusters.length > 0) {
    amber.push(`${p.siteClusters.length} site(s) with 2+ incidents in the current window`);
  }
  if (p.departmentClusters.length > 0) {
    amber.push(`${p.departmentClusters.length} department(s) with 2+ incidents in the current window`);
  }
  if (p.severityComparison.currentWindow.major > p.severityComparison.priorWindow.major) {
    amber.push(
      `Major-severity incidents increased from ${p.severityComparison.priorWindow.major} to ${p.severityComparison.currentWindow.major} versus the prior window`,
    );
  }

  return buildArea(
    'incident_patterns',
    'Incident Patterns',
    red,
    amber,
    'No fatal or critical incidents, no recurring root causes or location clusters, and major-severity incidents are not worsening',
    {
      fatalCurrentWindow: p.severityComparison.currentWindow.fatal,
      criticalCurrentWindow: p.severityComparison.currentWindow.critical,
      majorCurrentWindow: p.severityComparison.currentWindow.major,
      majorPriorWindow: p.severityComparison.priorWindow.major,
      recurringRootCausesCount: p.recurringRootCauses.length,
      siteClustersCount: p.siteClusters.length,
      departmentClustersCount: p.departmentClusters.length,
    },
  );
}

function evidenceArea(e: EvidenceCoverageSummary, thresholds?: ComplianceTwinThresholds): ComplianceTwinArea {
  const evidenceRedThreshold = thresholds?.evidenceRedThreshold ?? DEFAULT_EVIDENCE_RED_THRESHOLD;
  const evidenceAmberThreshold = thresholds?.evidenceAmberThreshold ?? DEFAULT_EVIDENCE_AMBER_THRESHOLD;
  const red: string[] = [];
  const amber: string[] = [];

  if (e.coveragePercent != null && e.coveragePercent < evidenceRedThreshold) {
    red.push(`Evidence coverage is ${Math.round(e.coveragePercent)}%, below the ${evidenceRedThreshold}% threshold`);
  } else if (e.coveragePercent != null && e.coveragePercent < evidenceAmberThreshold) {
    // Deliberately `else if`, not two independent checks — found in
    // Group 3's own adversarial review. Coverage below the RED
    // threshold is also, trivially, below the amber one; two
    // independent `if`s reported both facts together ("below 50%" and
    // "below 90%") as if they were separate findings, when they are
    // the same number crossing two thresholds at once. A red area
    // reports only its own, more severe, reason.
    amber.push(
      `Evidence coverage is ${Math.round(e.coveragePercent)}%, below the ${evidenceAmberThreshold}% threshold`,
    );
  }

  return buildArea(
    'evidence',
    'Evidence Coverage',
    red,
    amber,
    'Evidence coverage is at or above the 90% threshold (or no register completions have been recorded yet)',
    {
      coveragePercent: e.coveragePercent,
      evidenceRedThreshold,
      evidenceAmberThreshold,
    },
  );
}

export function assembleComplianceTwin(input: ComplianceTwinInput, thresholds?: ComplianceTwinThresholds): ComplianceTwinSnapshot {
  const areas: ComplianceTwinArea[] = [
    safetyArea(input.hsKpis, thresholds),
    governanceArea(input.governanceKpis, thresholds),
    riskGraphArea(input.riskGraph),
    incidentPatternsArea(input.incidentPatterns),
    evidenceArea(input.evidence, thresholds),
  ];

  return { overallBand: worstBand(areas.map(a => a.band)), areas };
}
