import { NextResponse, type NextRequest } from 'next/server';
import { z } from 'zod';
import { createServiceSupabaseClient } from '@/lib/supabase/service';
import { createRateLimiter, getRateLimitKey } from '@/lib/rateLimit';
import { loadWorkerQrStatus } from '@/lib/workforce/qrStatus';
import { parseBody } from '@/lib/validation/parseBody';
import { shortText, optionalShortText, optionalLongText } from '@/lib/validation/primitives';

// Worker QR badge → report a hazard with no login. Mirrors the
// report-incident route exactly: service-role insert (hs_hazard_guard()
// already skips its own session-only defaulting for a service-role
// connection — 201's own header comment), and the existing
// hazard_reported consequence rule (safetyRules.ts) reacts to the row
// regardless of how it was inserted, so no new notification wiring is
// needed. hazards' own CHECK requires a site or a location; hazards'
// `reference` is auto-generated by hs_hazard_guard() when left null.
//
// Field ceilings match hazards' own CHECK constraints exactly (title
// <=200, description <=4000, linked_location <=300).

const schema = z.object({
  title: shortText(200),
  description: optionalLongText(4000),
  location: optionalShortText(300),
});

const postLimiter = createRateLimiter({ windowMs: 5 * 60_000, max: 10 });

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

export async function POST(request: NextRequest, props: { params: Promise<{ token: string }> }) {
  if (!postLimiter.check(getRateLimitKey(request)).allowed) {
    return NextResponse.json({ error: 'Too many requests' }, { status: 429 });
  }

  const { token } = await props.params;
  const service = createServiceSupabaseClient();
  const status = await loadWorkerQrStatus(service, token);
  if (!status.ok || !status.companyId) return NextResponse.json({ error: 'Invalid link' }, { status: 404 });

  const parsed = await parseBody(request, schema);
  if (!parsed.ok) return parsed.response;
  const { title, description, location } = parsed.data;

  if (!status.siteId && !location) {
    return NextResponse.json({ error: 'Please describe where this is.' }, { status: 400 });
  }

  const { data, error } = await service.from('hazards').insert({
    company_id: status.companyId,
    site_id: status.siteId,
    linked_location: location,
    title,
    description,
    source: 'quick_report',
    reported_by_person_id: status.personId,
    reported_via: 'qr_scan',
  }).select('id, reference').single();

  if (error || !data) {
    return NextResponse.json({ error: error?.message ?? 'The report was not saved. Please try again.' }, { status: 500 });
  }

  return NextResponse.json({ ok: true, id: data.id, reference: data.reference });
}
